name: Deploy to IIS

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  build-and-deploy:
    runs-on: self-hosted   # your IIS server runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'   # updated to .NET 9

    - name: Restore dependencies
      run: dotnet restore devopswebapp/devopswebapp.csproj

    - name: Build
      run: dotnet build devopswebapp/devopswebapp.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish devopswebapp/devopswebapp.csproj -c Release -o ./publish

    - name: Deploy to IIS
      run: |
        Import-Module WebAdministration

        # Graceful app unload
        New-Item -Path "C:\inetpub\wwwroot\MyNewWebsite\app_offline.htm" -ItemType File -Force

        Stop-WebAppPool -Name "DefaultAppPool"

        # Clean old files
        Remove-Item "C:\inetpub\wwwroot\MyNewWebsite\*" -Recurse -Force

        # Copy new build
        Copy-Item ".\publish\*" "C:\inetpub\wwwroot\MyNewWebsite\" -Recurse -Force

        Start-WebAppPool -Name "DefaultAppPool"

        # Remove app_offline to bring site back online
        Remove-Item "C:\inetpub\wwwroot\MyNewWebsite\app_offline.htm" -Force
      shell: powershell
